// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJVHqXyW5Zs3QHsACyrEC17VPHacAS4o',
    appId: '1:163498960632:web:8442b88dfb2bd328373d0d',
    messagingSenderId: '163498960632',
    projectId: 'ambugo-ac78d',
    authDomain: 'ambugo-ac78d.firebaseapp.com',
    databaseURL: 'https://ambugo-ac78d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ambugo-ac78d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBi4-_c3Xp7NrwDDW-z2o_gtNVGDzSvc',
    appId: '1:163498960632:android:70f373aef65871a0373d0d',
    messagingSenderId: '163498960632',
    projectId: 'ambugo-ac78d',
    databaseURL: 'https://ambugo-ac78d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ambugo-ac78d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGHVtVRLOZ4PGl2OMLQUXs4MrDWiyHMA',
    appId: '1:163498960632:ios:65d22bc2515c5fd9373d0d',
    messagingSenderId: '163498960632',
    projectId: 'ambugo-ac78d',
    databaseURL: 'https://ambugo-ac78d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ambugo-ac78d.firebasestorage.app',
    iosBundleId: 'com.example.ambugoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGHVtVRLOZ4PGl2OMLQUXs4MrDWiyHMA',
    appId: '1:163498960632:ios:65d22bc2515c5fd9373d0d',
    messagingSenderId: '163498960632',
    projectId: 'ambugo-ac78d',
    databaseURL: 'https://ambugo-ac78d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ambugo-ac78d.firebasestorage.app',
    iosBundleId: 'com.example.ambugoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCJVHqXyW5Zs3QHsACyrEC17VPHacAS4o',
    appId: '1:163498960632:web:2939a08dc6f4eea4373d0d',
    messagingSenderId: '163498960632',
    projectId: 'ambugo-ac78d',
    authDomain: 'ambugo-ac78d.firebaseapp.com',
    databaseURL: 'https://ambugo-ac78d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ambugo-ac78d.firebasestorage.app',
  );
}
